apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-rs
  labels:
    app: mydb
    tier: db
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
      - name: redis
        image: redis
